name: Hello World Alertify
on: 
  push:
    branches:
        - github-actions/initial
jobs:
    helloworld:
        runs-on: macos-latest
        steps:
            - name: Hello World
              run: echo 'Hello World'
   
